[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/api/*"
  to = "https://primary-production-166e.up.railway.app/:splat"
  status = 200
  force = true
